In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

date_columns = [col for col in df.columns if 'date' in col]
close_columns = [col for col in df.columns if 'close' in col]

In [3]:
close = df[close_columns]

In [4]:
close["date"] = df["date_afran"]

C:\Users\shahram\AppData\Local\Temp\ipykernel_3300\1971520809.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  close["date"] = df["date_afran"]

In [5]:
close

,close_afran,close_yaghoot,close_goldMofid,close_nahal,close_sahar,close_agas,close_sarv,close_atlas,date
0,12663,11878,31124.36,9865.96,10908.05,69174.34,6360.23,20902.53,20210213
1,12670,11885,30422.25,9865.96,10460.16,67565.87,6227.35,20681.29,20210214
2,12679,11889,29835.98,9442.51,9787.82,66848.65,6194.58,20439.37,20210215
3,12699,11899,30236.31,9003.23,9680.08,65842.73,6099.01,20134.64,20210216
4,12711,11909,30045.29,9003.23,9772.85,66009.71,6114.49,19921.05,20210217
...,...,...,...,...,...,...,...,...,...
977,33442,29461,222502.00,37381.00,44718.00,173298.00,16660.00,57391.00,20250318
978,33559,29553,218976.00,37191.00,44591.00,178451.00,17140.00,59070.00,20250325
979,33598,29603,226735.00,37587.00,45100.00,181312.00,17220.00,59638.00,20250326
980,33666,29634,241248.00,38291.00,46077.00,180997.00,17300.00,59784.00,20250329
981,33765,29757,236934.00,38088.00,45382.00,184960.00,17660.00,60744.00,20250330

In [6]:
close['date'] = pd.to_datetime(close['date'], format='%Y%m%d')
close

C:\Users\shahram\AppData\Local\Temp\ipykernel_3300\357283283.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  close['date'] = pd.to_datetime(close['date'], format='%Y%m%d')

,close_afran,close_yaghoot,close_goldMofid,close_nahal,close_sahar,close_agas,close_sarv,close_atlas,date
0,12663,11878,31124.36,9865.96,10908.05,69174.34,6360.23,20902.53,2021-02-13
1,12670,11885,30422.25,9865.96,10460.16,67565.87,6227.35,20681.29,2021-02-14
2,12679,11889,29835.98,9442.51,9787.82,66848.65,6194.58,20439.37,2021-02-15
3,12699,11899,30236.31,9003.23,9680.08,65842.73,6099.01,20134.64,2021-02-16
4,12711,11909,30045.29,9003.23,9772.85,66009.71,6114.49,19921.05,2021-02-17
...,...,...,...,...,...,...,...,...,...
977,33442,29461,222502.00,37381.00,44718.00,173298.00,16660.00,57391.00,2025-03-18
978,33559,29553,218976.00,37191.00,44591.00,178451.00,17140.00,59070.00,2025-03-25
979,33598,29603,226735.00,37587.00,45100.00,181312.00,17220.00,59638.00,2025-03-26
980,33666,29634,241248.00,38291.00,46077.00,180997.00,17300.00,59784.00,2025-03-29
981,33765,29757,236934.00,38088.00,45382.00,184960.00,17660.00,60744.00,2025-03-30

In [7]:
close.set_index(close.date, inplace= True)

In [8]:
close.drop(columns=["date"], inplace=True)

C:\Users\shahram\AppData\Local\Temp\ipykernel_3300\1880331424.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  close.drop(columns=["date"], inplace=True)

In [9]:
close

,close_afran,close_yaghoot,close_goldMofid,close_nahal,close_sahar,close_agas,close_sarv,close_atlas
date,,,,,,,,
2021-02-13,12663,11878,31124.36,9865.96,10908.05,69174.34,6360.23,20902.53
2021-02-14,12670,11885,30422.25,9865.96,10460.16,67565.87,6227.35,20681.29
2021-02-15,12679,11889,29835.98,9442.51,9787.82,66848.65,6194.58,20439.37
2021-02-16,12699,11899,30236.31,9003.23,9680.08,65842.73,6099.01,20134.64
2021-02-17,12711,11909,30045.29,9003.23,9772.85,66009.71,6114.49,19921.05
...,...,...,...,...,...,...,...,...
2025-03-18,33442,29461,222502.00,37381.00,44718.00,173298.00,16660.00,57391.00
2025-03-25,33559,29553,218976.00,37191.00,44591.00,178451.00,17140.00,59070.00
2025-03-26,33598,29603,226735.00,37587.00,45100.00,181312.00,17220.00,59638.00
2025-03-29,33666,29634,241248.00,38291.00,46077.00,180997.00,17300.00,59784.00
2025-03-30,33765,29757,236934.00,38088.00,45382.00,184960.00,17660.00,60744.00

In [10]:
#close.to_csv("closeDate.csv")

In [11]:
log_returns = np.log(close/close.shift(1)).dropna()
# Rename columns from 'close_*' to 'ret_*'
log_returns.columns = [col.replace('close_', 'ret_') for col in log_returns.columns]

In [12]:
log_returns.to_csv("logRetData.csv")

In [13]:
simple_returns = (((close / close.shift(1)) - 1)*100).dropna()
# Rename columns from 'close_*' to 'ret_*'
simple_returns.columns = [col.replace('close_', 'ret_') for col in simple_returns.columns]

In [14]:
simple_returns.to_csv("simpleRetData.csv")